
testcode = ['<w:p w14:paraId="27E1BD8D" w14:textId="77777777" w:rsidR="00EE3670" w:rsidRDefault="00EE3670" w:rsidP="00EE3670">',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t xml:space="preserve">',
            '　その決着は一瞬だった。',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '|',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '倉持',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '恵',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '《',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            'くらもち',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            'めぐみ',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '》',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            'の抜き放った一閃が弾丸を切り裂き、',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '|',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '魂魄《こんぱく》兵装もろとも敵を両断する。',
            '</w:t>',
            '</w:r>',
            '</w:p>',
            '<w:p w14:paraId="1A318B7D" w14:textId="77777777" w:rsidR="00EE3670" w:rsidRDefault="00EE3670" w:rsidP="00EE3670">',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t xml:space="preserve">',
            '　鮮血が吹き上がる――',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '|',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '倉持',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '《',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            'くらもち',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '》',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '|',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '廻《めぐる》は身構えたが、そうはならなかった。',
            '</w:t>',
            '</w:r>',
            '</w:p>']


idealcode = ['<w:p w14:paraId="27E1BD8D" w14:textId="77777777" w:rsidR="00EE3670" w:rsidRDefault="00EE3670" w:rsidP="00EE3670">',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t xml:space="preserve">',
            '　その決着は一瞬だった。',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '|',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '倉持恵《くらもちめぐみ》の抜き放った一閃が弾丸を切り裂き、',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '|',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '魂魄《こんぱく》兵装もろとも敵を両断する。',
            '</w:t>',
            '</w:r>',
            '</w:p>',
            '<w:p w14:paraId="1A318B7D" w14:textId="77777777" w:rsidR="00EE3670" w:rsidRDefault="00EE3670" w:rsidP="00EE3670">',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t xml:space="preserve">',
            '　鮮血が吹き上がる――',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '|',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '倉持《くらもち》',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '|',
            '</w:t>',
            '</w:r>',
            '<w:r>',
            '<w:rPr>',
            '<w:rFonts w:hint="eastAsia"/>',
            '</w:rPr>',
            '<w:t>',
            '廻《めぐる》は身構えたが、そうはならなかった。',
            '</w:t>',
            '</w:r>',
            '</w:p>']
